-- 0018: profile 以 repo 現行版本覆蓋過期 D1 seed，並將 BitOGuard 全面改為已確認的 LightGBM。

INSERT OR REPLACE INTO sections (key, zh, en, updated_at) VALUES (
  'profile',
  '{"name":"江嘉元","title":"軟硬整合 · 從 PCB 到韌體到資料","bio":"機電整合科班出身，軟硬韌全鏈路都親手走過：機構設計、CNC 加工、PCB、嵌入式韌體，到資料分析與 AI 模型。電機系三年級，高職讀機電整合，所以每一層都實際碰過、也知道彼此怎麼銜接——跨背景合作時比較容易對焦。最近的 ICU VAP 時序預測研究已投稿 IEEE GCCE 2026。","avatar":"/455AD532-F2CF-492B-B26C-CEB9053049D5.jpg","contact":{"email":"johnjia9491@gmail.com","location":"台北市, 台灣"},"links":{"github":"Jcsk7049","linkedin":"jiayuan-jiang0901"}}',
  '{"name":"Chiang Jia Yuan","title":"Hardware/Software Integration · From PCB to Firmware to Data","bio":"Trained in mechatronics from the ground up — mechanical design, CNC machining, PCB, embedded firmware, through to data analysis and AI models. Third-year EE student with a vocational mechatronics background, so I''ve worked hands-on at every layer and know how they connect — which makes it easier to stay aligned when collaborating across disciplines. My latest research, on time-series prediction of ICU VAP, has been submitted to IEEE GCCE 2026.","avatar":"/455AD532-F2CF-492B-B26C-CEB9053049D5.jpg","contact":{"email":"johnjia9491@gmail.com","location":"Taipei, Taiwan"},"links":{"github":"Jcsk7049","linkedin":"jiayuan-jiang0901"}}',
  datetime('now')
);

UPDATE projects
SET zh = json_set(
  zh,
  '$.description', 'LightGBM × S3 → Glue → Athena → SageMaker → Lambda → Bedrock 六服務端對端 AML 管線；63,770 帳戶 / 413,235 筆交易，31 項行為特徵（含圖論黑名單鄰居）+ SHAP 合規報告識別人頭帳戶，Streamlit 儀表板已部署上線。',
  '$.tags', json('["LightGBM","AWS SageMaker","AWS Glue","SHAP","Streamlit"]'),
  '$.detail.purpose', 'BitoPro 加密貨幣交易所 AML 合規競賽資料集：\n・用戶資料：63,770 筆帳戶\n・台幣轉帳紀錄：195,601 筆（56,111 用戶）\n・USDT 交易紀錄：217,634 筆（33,587 用戶）\n・標記人頭帳戶：1,640 筆（訓練集 3.21%）\n\n目標是對每個帳戶輸出風險分數，識別高風險可疑帳戶，同時滿足監管機構對 AML 合規說明的可解釋性要求（不接受黑盒輸出）。\n\n選用 LightGBM 而非深度學習的理由：AML 合規場景要求對每筆標記帳戶提供特徵層級的判斷依據，LightGBM 搭配 SHAP 可直接輸出個別帳戶的特徵貢獻值；在 <65K 結構化資料規模下，樹模型適合處理這類表格資料，也能配合類別權重處理不平衡。',
  '$.detail.concept', '【為何選用 LightGBM，而非深度學習？】\nAML 合規系統的核心需求是可解釋性：監管機構要求對每筆標記帳戶提供「哪些特徵觸發高風險」的具體依據，而非黑盒分數。LightGBM 配合 SHAP 值分析可直接輸出每個特徵對單一帳戶預測的貢獻量，滿足合規說明義務。對這類結構化交易資料，樹模型也能以類別權重處理 1:30 的不平衡。\n\n【資料管線（AWS 端對端架構）】\n① BitoPro API 抓取交易紀錄 → ingest_to_s3.py 存入 AWS S3（原始資料層）\n② AWS Glue 執行 ETL 清洗 + glue_graph_hops.py 進行圖形化多跳關聯分析\n③ Amazon Athena 以 SQL 查詢聚合特徵結果（athena_graph_hops.sql）\n④ Amazon SageMaker 執行 LightGBM 模型訓練、調參與部署\n⑤ AWS Lambda + lambda_diagnosis.py 處理即時推論與事件觸發邏輯\n⑥ Amazon Bedrock 整合 SHAP + XAI，為每筆高風險帳戶自動產生可解釋性報告\n⑦ Streamlit 儀表板（app.py）提供互動式風險審查介面\n⑧ CloudFormation template.yaml 定義全套 IaC（基礎設施即程式碼）\n\n【特徵工程（31 項行為指標）】\n競賽提交版以三項核心特徵起步（台幣存提次數、深夜交易比例），競賽後持續擴充至 31 項，涵蓋：\n・交易行為：total_volume、tx_per_day、avg_twd_amount、swap_twd_volume\n・時序特徵：min_retention_minutes（最短持幣時間）、night_tx_ratio\n・圖論特徵：blacklist_neighbor_count（黑名單鄰居數）、is_direct_neighbor\n・風險旗標：high_speed_risk、ip_anomaly、deposit_only_flag\n特徵重要性最高的前三名依序為：total_volume（交易總量）、age（帳戶年齡）、swap_twd_volume（換匯金額）\n\n【模型設計】\n・LightGBM 梯度提升分類器\n・以 max_depth、learning_rate、num_iterations 與類別權重控制模型複雜度與不平衡\n・5-fold Stratified CV，確保每折正負樣本比例一致\n・決策閾值掃描，依 Precision 與 Recall 的取捨選擇工作點\n・SHAP 值分析呈現每個特徵對個別帳戶預測的貢獻度',
  '$.detail.outcome', '【競賽成果】\n・完賽 AWS x BitoPro 黑客松，端對端雲端架構設計獲評審正面評價\n・81 commits，完整實作從 API 資料擷取到模型預測的全管線\n\n【技術成果】\n・成功串接六項 AWS 服務：SageMaker、Glue、Athena、Lambda、S3、Bedrock\n・特徵工程從競賽初版 3 項擴充至 31 項行為指標\n・SHAP 可解釋性模組讓模型判斷具備合規說明能力\n・Streamlit 儀表板支援帳戶風險互動審查，已部署上線\n\n【模型效能（儀表板版本）】\n・AUC：83.2%\n・Precision：27.5%\n・Recall：33.2%\n・F1 Score：30.1%\n・Accuracy：95.0%\n・標記為風險帳戶：501 / 12,753\n\n這組數字來自已部署的 BitoGuard 儀表板；Accuracy 受資料不平衡影響，不單獨作為模型好壞的判斷。Precision 與 Recall 一起呈現，讓誤報成本和找出風險帳戶的能力都能被看見。',
  '$.detail.tech[0].items[0].desc', '以 LightGBM 處理不平衡二元分類；透過 max_depth、learning_rate、num_iterations 與類別權重調整模型，並以決策閾值比較 Precision 與 Recall 的取捨',
  '$.detail.pipeline[3].label', 'LightGBM 訓練與調參'
),
en = json_set(
  en,
  '$.description', 'LightGBM × S3→Glue→Athena→SageMaker→Lambda→Bedrock end-to-end AML pipeline; 63,770 accounts / 413,235 transactions; 31 behavioral features (incl. graph-theory blacklist neighbors) + SHAP compliance reports to identify money mule accounts. Streamlit dashboard live.',
  '$.tags', json('["LightGBM","AWS SageMaker","AWS Glue","SHAP","Streamlit"]'),
  '$.detail.purpose', 'BitoPro cryptocurrency exchange AML compliance competition dataset:\n- User records: 63,770 accounts\n- TWD transfer records: 195,601 (56,111 users)\n- USDT transaction records: 217,634 (33,587 users)\n- Labeled money mule accounts: 1,640 (3.21% of training set)\n\nGoal: output a risk score per account to identify high-risk suspicious accounts while satisfying regulators'' demand for explainability in AML compliance (black-box outputs not accepted).\n\nWhy LightGBM over deep learning:\nAML compliance requires feature-level justification for every flagged account. LightGBM with SHAP directly outputs each feature''s contribution per account. For structured data at this scale, a tree model also supports class weighting for the imbalanced labels.',
  '$.detail.concept', '[Why LightGBM, Not Deep Learning?]\nAML compliance systems require explainability: regulators demand "which features triggered high risk" for every flagged account. LightGBM with SHAP values directly outputs per-feature contributions for individual accounts, meeting compliance reporting requirements. For structured transactional data, a tree model can also use class weighting for the 1:30 imbalance.\n\n[Data Pipeline — AWS End-to-End Architecture]\n① BitoPro API ingestion → ingest_to_s3.py → AWS S3 (raw data layer)\n② AWS Glue ETL + glue_graph_hops.py for graph-based multi-hop association analysis\n③ Amazon Athena SQL queries to aggregate feature results (athena_graph_hops.sql)\n④ Amazon SageMaker for LightGBM training, tuning, and deployment\n⑤ AWS Lambda + lambda_diagnosis.py for real-time inference and event-driven logic\n⑥ Amazon Bedrock integrates SHAP + XAI to auto-generate explainability reports per high-risk account\n⑦ Streamlit dashboard (app.py) for interactive risk review\n⑧ CloudFormation template.yaml defines full IaC\n\n[Feature Engineering — 31 Behavioral Indicators]\nCompetition version started with 3 core features (TWD deposit/withdrawal count, late-night transaction ratio), expanded post-competition to 31 indicators:\n- Transaction behavior: total_volume, tx_per_day, avg_twd_amount, swap_twd_volume\n- Temporal features: min_retention_minutes, night_tx_ratio\n- Graph features: blacklist_neighbor_count, is_direct_neighbor\n- Risk flags: high_speed_risk, ip_anomaly, deposit_only_flag\nTop 3 by importance: total_volume, account age, swap_twd_volume\n\n[Model Design]\n- LightGBM gradient-boosting classifier\n- max_depth, learning_rate, num_iterations, and class weighting control model complexity and imbalance\n- 5-fold Stratified CV with consistent positive/negative ratios per fold\n- Decision-threshold sweeps compare the precision/recall trade-off\n- SHAP analysis shows per-feature contribution for individual accounts',
  '$.detail.outcome', '[Competition Result]\n- Completed AWS × BitoPro Hackathon; end-to-end cloud architecture received positive feedback from judges\n- 81 commits, fully implementing the pipeline from API data ingestion to model prediction\n\n[Technical Achievements]\n- Successfully chained 6 AWS services: SageMaker, Glue, Athena, Lambda, S3, Bedrock\n- Feature engineering expanded from 3 competition features to 31 behavioral indicators\n- SHAP interpretability module provides AML-compliant explanations\n- Streamlit dashboard supports interactive account risk review — deployed live\n\n[Model Performance — Dashboard Version]\n- AUC: 83.2%\n- Precision: 27.5%\n- Recall: 33.2%\n- F1 Score: 30.1%\n- Accuracy: 95.0%\n- Accounts flagged as risky: 501 / 12,753\n\nThese figures come from the deployed BitoGuard dashboard. Accuracy is affected by class imbalance, so it is not used alone to judge the model; precision and recall are presented together to show both false-positive cost and risk-account coverage.',
  '$.detail.tech[0].items[0].desc', 'LightGBM for imbalanced binary classification; tune max_depth, learning_rate, num_iterations, and class weighting, then compare precision and recall across decision thresholds',
  '$.detail.pipeline[3].label', 'LightGBM training & tuning'
)
WHERE id = 'aws-hackathon';

-- Use this diagnostic before applying only if the old wording must be located first:
-- SELECT key, json_extract(zh, '$.title') AS zh_title, json_extract(en, '$.title') AS en_title
-- FROM sections
-- WHERE zh LIKE '%軟體到韌體%' OR en LIKE '%Software%Firmware%';
